export const ASSET_CREATE = "ASSET_CREATE";
export const ASSET_CREATE_PAGE_LOADED = "ASSET_CREATE_PAGE_LOADED";
export const ASSET_CREATE_PAGE_UNLOADED = "ASSET_CREATE_PAGE_UNLOADED";
export const ASSET_UPDATE = "ASSET_UPDATE";
export const ASSET_UPDATE_PAGE_UNLOADED = "ASSET_UPDATE_PAGE_UNLOADED";
export const ASSET_LIST_PAGE_LOADED = "ASSET_LIST_PAGE_LOADED";
export const ASSET_LIST_PAGE_UNLOADED = "ASSET_LIST_PAGE_UNLOADED";
export const ASSET_DETAIL_PAGE_LOADED = "ASSET_DETAIL_PAGE_LOADED";
export const ASSET_DETAIL_PAGE_UNLOADED = "ASSET_DETAIL_PAGE_UNLOADED";

export const SITE_CREATE = "SITE_CREATE";
export const SITE_LIST_PAGE_LOADED = "SITE_LIST_PAGE_LOADED";
export const SITE_LIST_PAGE_UNLOADED = "SITE_LIST_PAGE_UNLOADED";
export const SITE_DETAIL_PAGE_LOADED = "SITE_DETAIL_PAGE_LOADED";
export const SITE_DETAIL_PAGE_UNLOADED = "SITE_DETAIL_PAGE_UNLOADED";

export const LOG_EVENT = "LOG_EVENT";
export const EVENT_ADD_PAGE_LOADED = "EVENT_ADD_PAGE_LOADED";
export const EVENT_ADD_PAGE_UNLOADED = "EVENT_ADD_PAGE_UNLOADED";
